version: "3.9"
services:
        web:
            build: ./
            command: nodemon -L server.js
            ports:
                - "3000:3000"
            volumes:
                - ./:/usr/src/app
                - /usr/src/app/node_modules
            depends_on:
                - mongo
        mongo:
            image: mongo
            ports: 
                - "27017:27017"
            volumes:
                - ./data:/data/db